# Generated by Django 5.0.4 on 2025-03-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['time']},
        ),
        migrations.RenameField(
            model_name='status',
            old_name='timestamp',
            new_name='time',
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('trip', 'time')},
        ),
    ]
