# Generated by Django 5.0.4 on 2025-03-31 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylog',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='dailylog',
            name='unique_daily_log_date',
        ),
    ]
