# Generated by Django 5.0.4 on 2025-03-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucking_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='license_expiration',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='make',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vin',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='year',
        ),
    ]
