# Generated by Django 5.0.4 on 2025-03-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucking_app', '0002_remove_driver_license_expiration_remove_vehicle_make_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylog',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='statuslog',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='driver',
        ),
        migrations.AlterModelOptions(
            name='statuslog',
            options={'ordering': ['-time']},
        ),
        migrations.RenameField(
            model_name='statuslog',
            old_name='start_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
