# Generated by Django 5.0.4 on 2025-03-28 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucking_app', '0003_remove_dailylog_driver_remove_statuslog_driver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='destination',
            new_name='destination_latitude',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='start_location',
            new_name='destination_longitude',
        ),
        migrations.AddField(
            model_name='trip',
            name='start_latitude',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='start_longitude',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
