# Generated by Django 5.0.4 on 2025-03-29 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucking_app', '0016_remove_dailylog_vehicle_alter_dailylog_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='total_on_duty_hours',
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='trip',
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='trip',
            field=models.ManyToManyField(blank=True, help_text='Trips associated with this daily log', related_name='daily_logs', to='trucking_app.trip'),
        ),
    ]
