# Generated by Django 5.0.4 on 2025-03-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucking_app', '0017_remove_trip_total_on_duty_hours_alter_dailylog_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='total_distance_km',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_duration_hours',
            field=models.FloatField(default=0),
        ),
    ]
