# Generated by Django 5.0.4 on 2025-03-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucking_app', '0018_trip_total_distance_km_trip_total_duration_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='cumulative_mileage',
            field=models.FloatField(default=0, help_text='Total odometer reading'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='total_miles',
            field=models.FloatField(default=0, help_text='Miles driven today'),
        ),
    ]
